# ros1 example
# lidar_name: foo
# lidar_id: 10
# ports: [11312, 11311, 21311]
# debug: true

# ros2 example
/lidar_ns:
  lidar_node_name:
    ros__parameters:
      lidar_name: foo
      id: 10
imu:
  ros__parameters:
    ports: [2438, 2439, 2440]
/**:
  ros__parameters:
    debug: true